title: GarrettTech's homepage 
description: GitHub Pages example for promoting a project
github_username: GarrettTech #my name 
remote_theme: pages-themes/hacker@v0.2.0 #edit theme 10/6
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
